#!/usr/bin/env python3
"""
Cloud Credits Tracker — Ranuk IT Solutions
Extrae y organiza deals de créditos cloud detectados.
Genera resumen en consola + next_steps.txt con instrucciones para aplicar.
"""

import datetime
import os

DEALS = [
    {
        "provider": "Nebula AI",
        "credits": "$500",
        "link": "https://nebula.example.com/startup-program",
        "benefit": "Free compute credits for AI/ML workloads (startups)",
        "requirements": "GitHub account, startup application form",
        "validity": "90 days from activation",
    },
    {
        "provider": "AWS Activate",
        "credits": "$1,000",
        "link": "https://aws.amazon.com/activate",
        "benefit": "AWS startup credits package (EC2, S3, Lambda, etc.)",
        "requirements": "Startup or founder account, GitHub Student eligible",
        "validity": "1-2 years",
    },
    {
        "provider": "Google Cloud for Startups",
        "credits": "$200",
        "link": "https://cloud.google.com/startup",
        "benefit": "GCP credits for compute, storage, AI APIs",
        "requirements": "Google account, startup program application",
        "validity": "60 days",
    },
    {
        "provider": "Microsoft Azure for Startups",
        "credits": "$5,000",
        "link": "https://www.microsoft.com/en-us/startups",
        "benefit": "Azure credits + GitHub Enterprise + technical support",
        "requirements": "Microsoft for Startups Founders Hub signup",
        "validity": "1 year",
    },
    {
        "provider": "DigitalOcean Hatch",
        "credits": "$200",
        "link": "https://www.digitalocean.com/hatch",
        "benefit": "Droplets, managed databases, Spaces, App Platform",
        "requirements": "Startup program application",
        "validity": "1 year",
    },
]

NEXT_STEPS_FILE = "next_steps.txt"
SEPARATOR = "-" * 60


def print_summary(deals: list[dict]) -> None:
    """Print a formatted summary of all detected deals to console."""
    today = datetime.date.today().isoformat()
    print(f"\n{'=' * 60}")
    print(f"  ☁️  CLOUD CREDITS TRACKER — {today}")
    print(f"  Detected deals: {len(deals)}")
    print(f"{'=' * 60}\n")

    for i, deal in enumerate(deals, 1):
        print(f"  {i}. {deal['provider']}")
        print(f"     💰 Credits: {deal['credits']}")
        print(f"     🔗 Link:    {deal['link']}")
        print(f"     📋 Benefit: {deal['benefit']}")
        print(f"     ⏳ Valid:   {deal['validity']}")
        print()

    total_approx = sum(
        int(d["credits"].replace("$", "").replace(",", ""))
        for d in deals
        if d["credits"].startswith("$")
    )
    print(SEPARATOR)
    print(f"  🏦 Total approximate credits available: ${total_approx:,}")
    print(f"{'=' * 60}\n")


def generate_next_steps(deals: list[dict], output_path: str) -> None:
    """Write actionable next steps to a text file."""
    today = datetime.date.today().isoformat()
    lines = [
        f"Cloud Credits — Next Steps ({today})",
        SEPARATOR,
        "",
    ]

    for i, deal in enumerate(deals, 1):
        lines.extend([
            f"[{i}] {deal['provider']} — {deal['credits']}",
            f"    Link: {deal['link']}",
            f"    Benefit: {deal['benefit']}",
            f"    Requirements: {deal['requirements']}",
            f"    Validity: {deal['validity']}",
            f"    ACTION: Visit the link above, complete the application,",
            f"    and activate credits. Save credentials in password manager.",
            "",
        ])

    lines.extend([
        SEPARATOR,
        "Priority order: Azure ($5k) → AWS ($1k) → Nebula ($500) → DO ($200) → GCP ($200)",
        "",
        "Generated by Cloud Credits Tracker — Ranuk IT Solutions",
    ])

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"✅ Next steps saved to: {os.path.abspath(output_path)}")


def main() -> None:
    print_summary(DEALS)
    generate_next_steps(DEALS, NEXT_STEPS_FILE)


if __name__ == "__main__":
    main()
